<h3>EDA analysis of datasets</h3>

<h4>Flight sample dataset</h4>

In [1]:
import pandas as pd

<p>Download and save parquet file with flight data</p>

In [9]:
!wget -O ./data/flight_sample.parquet https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202501.parquet

--2026-03-21 14:18:18--  https://www.eurocontrol.int/performance/data/download/OPDI/v002/flight_list/flight_list_202501.parquet
Resolving www.eurocontrol.int (www.eurocontrol.int)... 104.18.10.65, 104.18.11.65, 2606:4700::6812:b41, ...
Connecting to www.eurocontrol.int (www.eurocontrol.int)|104.18.10.65|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33922640 (32M)
Saving to: ‘./data/flight_sample.parquet’

./data/flight_sampl 100%[===================>]  32.35M  6.14MB/s    in 5.5s

2026-03-21 14:18:24 (5.87 MB/s) - ‘./data/flight_sample.parquet’ saved [33922640/33922640]

<p>Observe the dataframe</p>

In [11]:
data = pd.read_parquet('./data/flight_sample.parquet')

In [31]:
data.head(20)

,id,icao24,flt_id,dof,adep,ades,adep_p,ades_p,registration,model,typecode,icao_aircraft_class,icao_operator,first_seen,last_seen,version,unix_time
0,3488005984615,4baa93,TKJ1DK,2025-01-01,LTFJ,NaN,,,NaN,NaN,NaN,NaN,NaN,2025-01-01 14:24:40,2025-01-01 14:47:45,v2.0.0,1735741480
1,5868520310734,4867b0,TRA6411,2025-01-31,EHAM,NaN,,,NaN,NaN,NaN,NaN,NaN,2025-01-31 07:39:50,2025-01-31 09:34:45,v2.0.0,1738309190
2,15826809206891,0a0089,NaN,2025-01-25,NaN,NaN,NaN,NaN,7T-VUW,ATR 72 600,AT76,L2T,DAH,2025-01-25 18:12:25,2025-01-25 18:20:00,v2.0.0,1737828745
3,21477029090992,447c52,,2025-01-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-28 09:07:30,2025-01-28 09:13:10,v2.0.0,1738055250
4,29235037659640,4d2502,RYR404A,2025-01-11,LPPR,LEBL,,,9H-VVQ,Boeing 737 MAX 8-200,B38M,NaN,RYR,2025-01-11 09:09:25,2025-01-11 10:32:45,v2.0.0,1736586565
5,41158732645012,4856c9,KLM7925,2025-01-29,NaN,NaN,NaN,NaN,PH-KFC,NaN,DA42,L2P,NaN,2025-01-29 06:44:50,2025-01-29 06:51:30,v2.0.0,1738133090
6,43481741877832,3c56ee,EWG1CR,2025-01-04,EDDH,NaN,,,D-AEWN,A320 214SL,A320,L2J,EWG,2025-01-04 12:46:10,2025-01-04 16:39:45,v2.0.0,1735994770
7,55432238206495,4bcdd5,SXS4F,2025-01-09,LTBJ,NaN,,,TC-SNU,737NG 8HC/W,B738,L2J,SXS,2025-01-09 16:40:55,2025-01-09 18:17:25,v2.0.0,1736440855
8,60656829030530,39260d,FGJQN,2025-01-17,LFRI,NaN,,,F-GJQN,DR.400 180 Regent,DR40,L1P,NaN,2025-01-17 14:36:40,2025-01-17 14:45:15,v2.0.0,1737124600
9,97375436269383,407dcd,BCI554,2025-01-31,EGJJ,EGNX,,,G-ISLO,ATR 72-500,AT75,L2T,BCI,2025-01-31 13:44:55,2025-01-31 14:52:45,v2.0.0,1738331095
10,100867123757222,47bf10,DOC88,2025-01-03,EKOD,EKRK,,,LN-OUK,NaN,EC35,H2T,NaN,2025-01-03 20:24:20,2025-01-03 20:52:40,v2.0.0,1735935860
11,131421262909327,3c658c,,2025-01-11,NaN,ENZV,,,D-AILL,A319 114,A319,L2J,DLH,2025-01-11 10:46:00,2025-01-11 10:53:05,v2.0.0,1736592360
12,132507638280761,395141,METAL85,2025-01-09,LFCY,LFBG,,,F-GUKB,G-120,G120,L1P,FAF,2025-01-09 13:19:35,2025-01-09 14:34:20,v2.0.0,1736428775
13,146823227995870,48088b,,2025-01-09,EHVK,NaN,EHGR,,NaN,NaN,NaN,NaN,NaN,2025-01-09 14:37:30,2025-01-09 14:38:00,v2.0.0,1736433450
14,150467549821426,4b447c,AHE901,2025-01-20,LSMD,LSMA,,,HB-ZYI,NaN,B429,H2T,NaN,2025-01-20 10:21:05,2025-01-20 10:31:10,v2.0.0,1737368465
15,199954066104342,493284,NJE816C,2025-01-18,LFMN,LSZH,,,CS-LTD,Textron Aviation Citation Latitude,C68A,L2J,NaN,2025-01-18 10:55:20,2025-01-18 11:49:50,v2.0.0,1737197720
16,211283329382548,3c70b3,BCS1730,2025-01-28,EBBR,NaN,,,D-ALES,757-2Q8PCF,B752,L2J,BCS,2025-01-28 02:59:55,2025-01-28 03:59:55,v2.0.0,1738033195
17,232659967406349,4bcde7,NaN,2025-01-22,NaN,NaN,NaN,NaN,TC-SOG,737NG 800/W,B738,L2J,SXS,2025-01-22 10:33:40,2025-01-22 10:42:55,v2.0.0,1737542020
18,272073906933374,7105b1,SVA373,2025-01-22,NaN,NaN,NaN,NaN,HZ-AR32,NaN,B78X,L2J,NaN,2025-01-22 06:37:05,2025-01-22 06:42:55,v2.0.0,1737527825
19,303988407542823,4073a4,GPOPG,2025-01-02,EGVN,EGWC,EGVA,,G-POPG,EUROFOX 2K,UNDEFINED,NaN,NaN,2025-01-02 10:49:20,2025-01-02 12:07:15,v2.0.0,1735814960

In [16]:
data.columns

Index(['id', 'icao24', 'flt_id', 'dof', 'adep', 'ades', 'adep_p', 'ades_p',
       'registration', 'model', 'typecode', 'icao_aircraft_class',
       'icao_operator', 'first_seen', 'last_seen', 'version', 'unix_time'],
      dtype='str')

In [17]:
data.info

<bound method DataFrame.info of                            id  icao24    flt_id        dof  adep  ades adep_p  \
0               3488005984615  4baa93  TKJ1DK   2025-01-01  LTFJ   NaN
1               5868520310734  4867b0  TRA6411  2025-01-31  EHAM   NaN
2              15826809206891  0a0089       NaN 2025-01-25   NaN   NaN    NaN
3              21477029090992  447c52           2025-01-28   NaN   NaN    NaN
4              29235037659640  4d2502  RYR404A  2025-01-11  LPPR  LEBL
...                       ...     ...       ...        ...   ...   ...    ...
1036083  18446645549571433878  503d79  AHY064   2025-01-02  EDDB   NaN
1036084  18446688588963210670  4d23f8  RYR9XU   2025-01-25  EDDK   NaN
1036085  18446714180884428886  398de4  FHDPE    2025-01-21   NaN   NaN    NaN
1036086  18446739526091475838  486802  KLM1322  2025-01-24  EPKK  EHAM
1036087  18446740993063977924  407598  BZE03A   2025-01-22   NaN   NaN    NaN

        ades_p registration                 model typecode  \
0                       NaN                   NaN      NaN
1                       NaN                   NaN      NaN
2          NaN       7T-VUW            ATR 72 600     AT76
3          NaN          NaN                   NaN      NaN
4                    9H-VVQ  Boeing 737 MAX 8-200     B38M
...        ...          ...                   ...      ...
1036083              LY-JAM       Airbus A320-233     A320
1036084              9H-VVD                   NaN     B38M
1036085    NaN       F-HDPE  PA-28 181 Archer III     P28A
1036086                 NaN                   NaN      NaN
1036087    NaN       G-ZNTJ            Learjet 75     LJ75

        icao_aircraft_class icao_operator          first_seen  \
0                       NaN           NaN 2025-01-01 14:24:40
1                       NaN           NaN 2025-01-31 07:39:50
2                       L2T           DAH 2025-01-25 18:12:25
3                       NaN           NaN 2025-01-28 09:07:30
4                       NaN           RYR 2025-01-11 09:09:25
...                     ...           ...                 ...
1036083                 NaN           AHY 2025-01-02 09:55:25
1036084                 L2J           NaN 2025-01-25 14:06:40
1036085                 L1P           NaN 2025-01-21 15:05:45
1036086                 NaN           NaN 2025-01-24 08:20:40
1036087                 L2J           BZE 2025-01-22 06:50:15

                  last_seen version   unix_time
0       2025-01-01 14:47:45  v2.0.0  1735741480
1       2025-01-31 09:34:45  v2.0.0  1738309190
2       2025-01-25 18:20:00  v2.0.0  1737828745
3       2025-01-28 09:13:10  v2.0.0  1738055250
4       2025-01-11 10:32:45  v2.0.0  1736586565
...                     ...     ...         ...
1036083 2025-01-02 11:59:55  v2.0.0  1735811725
1036084 2025-01-25 17:25:35  v2.0.0  1737814000
1036085 2025-01-21 15:14:50  v2.0.0  1737471945
1036086 2025-01-24 10:09:45  v2.0.0  1737706840
1036087 2025-01-22 08:23:35  v2.0.0  1737528615

[1036088 rows x 17 columns]>

In [18]:
data.describe(include="all")

,id,icao24,flt_id,dof,adep,ades,adep_p,ades_p,registration,model,typecode,icao_aircraft_class,icao_operator,first_seen,last_seen,version,unix_time
count,1.036088e+06,1036088,943975,1036088,509668,553165,727539,727539,920708,665879,918795,777051,579091,1036088,1036088,1036088,1.036088e+06
unique,NaN,28314,88556,NaN,770,877,473,802,24035,3740,752,23,757,NaN,NaN,1,NaN
top,NaN,5113e1,,NaN,EGLL,EGLL,,,GND,A320 214,B738,L2J,RYR,NaN,NaN,v2.0.0,NaN
freq,NaN,459,19245,NaN,18302,18062,721233,711518,2434,21881,128428,624067,42724,NaN,NaN,1036088,NaN
mean,9.223361e+18,NaN,NaN,2025-01-15 06:00:03.419015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-15 18:30:00.622781,2025-01-15 19:47:21.922106,NaN,1.736966e+09
min,3.488006e+12,NaN,NaN,2025-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-01 00:00:00,2025-01-01 00:00:35,NaN,1.735690e+09
25%,4.615414e+18,NaN,NaN,2025-01-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-08 05:29:25,2025-01-08 06:41:48.750000,NaN,1.736314e+09
50%,9.226621e+18,NaN,NaN,2025-01-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-15 10:19:27.500000,2025-01-15 11:36:02.500000,NaN,1.736936e+09
75%,1.383464e+19,NaN,NaN,2025-01-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-22 18:46:40,2025-01-22 19:59:55,NaN,1.737572e+09
max,1.844674e+19,NaN,NaN,2025-01-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-31 23:59:30,2025-01-31 23:59:55,NaN,1.738368e+09
std,5.322051e+18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.655878e+05

In [19]:
data.nunique()

id                     1035898
icao24                   28314
flt_id                   88556
dof                         31
adep                       770
ades                       877
adep_p                     473
ades_p                     802
registration             24035
model                     3740
typecode                   752
icao_aircraft_class         23
icao_operator              757
first_seen              396259
last_seen               385550
version                      1
unix_time               396259
dtype: int64

In [20]:
data.shape

(1036088, 17)

In [22]:
data.duplicated('id')

0          False
1          False
2          False
3          False
4          False
           ...
1036083    False
1036084    False
1036085    False
1036086    False
1036087    False
Length: 1036088, dtype: bool

<p>check for possible duplicate id</p>

In [25]:
data_duplicated = data[data['id'].duplicated(keep=False)]

In [26]:
data_duplicated.to_csv('./data/duplicated.csv')

In [27]:
data_duplicated.shape

(380, 17)

<p>datatypes</p>

In [28]:
data.dtypes

id                             uint64
icao24                            str
flt_id                            str
dof                    datetime64[us]
adep                              str
ades                              str
adep_p                            str
ades_p                            str
registration                      str
model                             str
typecode                          str
icao_aircraft_class               str
icao_operator                     str
first_seen             datetime64[us]
last_seen              datetime64[us]
version                           str
unix_time                       int64
dtype: object

<p>Persentage of null values</p>

In [37]:
data.isna().mean()

id                     0.000000
icao24                 0.000000
flt_id                 0.088905
dof                    0.000000
adep                   0.508084
ades                   0.466102
adep_p                 0.297802
ades_p                 0.297802
registration           0.111361
model                  0.357314
typecode               0.113208
icao_aircraft_class    0.250014
icao_operator          0.441079
first_seen             0.000000
last_seen              0.000000
version                0.000000
unix_time              0.000000
dtype: float64

In [35]:
data[data['flt_id'].isna()].head()

,id,icao24,flt_id,dof,adep,ades,adep_p,ades_p,registration,model,typecode,icao_aircraft_class,icao_operator,first_seen,last_seen,version,unix_time
2,15826809206891,0a0089,NaN,2025-01-25,NaN,NaN,NaN,NaN,7T-VUW,ATR 72 600,AT76,L2T,DAH,2025-01-25 18:12:25,2025-01-25 18:20:00,v2.0.0,1737828745
17,232659967406349,4bcde7,NaN,2025-01-22,NaN,NaN,NaN,NaN,TC-SOG,737NG 800/W,B738,L2J,SXS,2025-01-22 10:33:40,2025-01-22 10:42:55,v2.0.0,1737542020
25,424562569716327,4ca3e3,NaN,2025-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-02 07:38:05,2025-01-02 08:10:40,v2.0.0,1735803485
26,437309451548656,47bf37,NaN,2025-01-10,NaN,NaN,NaN,NaN,LN-OUJ,H135,EC35,H2T,DOC,2025-01-10 13:17:50,2025-01-10 13:30:30,v2.0.0,1736515070
43,791592936167435,a3ea54,NaN,2025-01-20,NaN,NaN,NaN,NaN,N351UP,767-34AF,B763,L2J,UPS,2025-01-20 01:09:35,2025-01-20 01:23:35,v2.0.0,1737335375

<h4>Airports dataset</h4>

<p>Download and save dataset</p>

In [39]:
!wget -P ./data/ https://davidmegginson.github.io/ourairports-data/airports.csv

--2026-03-21 15:12:37--  https://davidmegginson.github.io/ourairports-data/airports.csv
Resolving davidmegginson.github.io (davidmegginson.github.io)... 185.199.109.153, 185.199.110.153, 185.199.108.153, ...
Connecting to davidmegginson.github.io (davidmegginson.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12563575 (12M) [text/csv]
Saving to: ‘./data/airports.csv’

airports.csv        100%[===================>]  11.98M  5.98MB/s    in 2.0s

2026-03-21 15:12:40 (5.98 MB/s) - ‘./data/airports.csv’ saved [12563575/12563575]

<p>Observe the dataframe</p>

In [40]:
airp = pd.read_csv('./data/airports.csv')

In [42]:
airp.head(20)

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,icao_code,iata_code,gps_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total RF Heliport,40.070985,-74.933689,11.0,NaN,US,US-PA,Bensalem,no,NaN,NaN,K00A,00A,https://www.penndot.pa.gov/TravelInPA/airports...,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,NaN,NaN,00AA,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,NaN,NaN,00AK,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,NaN,NaN,00AL,00AL,NaN,NaN,NaN
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NaN,US,US-AK,King Salmon,no,NaN,NaN,00AN,00AN,NaN,NaN,NaN
5,322127,00AS,small_airport,Fulton Airport,34.942803,-97.818019,1100.0,NaN,US,US-OK,Alex,no,NaN,NaN,00AS,00AS,NaN,NaN,NaN
6,6527,00AZ,small_airport,Cordes Airport,34.305599,-112.165001,3810.0,NaN,US,US-AZ,Cordes,no,NaN,NaN,00AZ,00AZ,NaN,NaN,NaN
7,6528,00CA,small_airport,Goldstone (GTS) Airport,35.354740,-116.885329,3038.0,NaN,US,US-CA,Barstow,no,NaN,NaN,00CA,00CA,NaN,https://en.wikipedia.org/wiki/Goldstone_Gts_Ai...,NaN
8,324424,00CL,small_airport,Williams Ag Airport,39.427188,-121.763427,87.0,NaN,US,US-CA,Biggs,no,NaN,NaN,00CL,00CL,NaN,NaN,NaN
9,322658,00CN,heliport,Kitchen Creek Helibase Heliport,32.727374,-116.459742,3350.0,NaN,US,US-CA,Pine Valley,no,NaN,NaN,00CN,00CN,NaN,NaN,NaN
10,6531,00FA,small_airport,Grass Patch Airport,28.645500,-82.219002,53.0,NaN,US,US-FL,Bushnell,no,NaN,NaN,00FA,00FA,NaN,NaN,NaN
11,6533,00FL,small_airport,River Oak Airport,27.230900,-80.969200,35.0,NaN,US,US-FL,Okeechobee,no,NaN,NaN,00FL,00FL,NaN,NaN,NaN
12,6534,00GA,small_airport,Lt World Airport,33.767502,-84.068298,700.0,NaN,US,US-GA,Lithonia,no,NaN,NaN,00GA,00GA,NaN,NaN,NaN
13,6535,00GE,heliport,Caffrey Heliport,33.887982,-84.736983,957.0,NaN,US,US-GA,Hiram,no,NaN,NaN,00GE,00GE,NaN,NaN,NaN
14,6536,00HI,heliport,Kaupulehu Heliport,19.832881,-155.978347,43.0,OC,US,US-HI,Kailua-Kona,no,NaN,NaN,00HI,00HI,NaN,NaN,NaN
15,6537,00ID,small_airport,Delta Shores Airport,48.145302,-116.213997,2064.0,NaN,US,US-ID,Clark Fork,no,NaN,NaN,00ID,00ID,NaN,NaN,NaN
16,322581,00IG,small_airport,Goltl Airport,39.724028,-101.395994,3359.0,NaN,US,US-KS,McDonald,no,NaN,NaN,00IG,00IG,NaN,NaN,NaN
17,6539,00IL,small_airport,Hammer Airport,41.978401,-89.560402,840.0,NaN,US,US-IL,Polo,no,NaN,NaN,00IL,00IL,NaN,NaN,Radio Ranch
18,6540,00IN,heliport,St Mary Medical Center Heliport,41.511398,-87.260597,634.0,NaN,US,US-IN,Hobart,no,NaN,NaN,00IN,00IN,NaN,NaN,NaN
19,6541,00IS,small_airport,Hayenga's Cant Find Farms Airport,40.025600,-89.122902,820.0,NaN,US,US-IL,Kings,no,NaN,NaN,00IS,00IS,NaN,NaN,NaN

In [46]:
airp.columns

Index(['id', 'ident', 'type', 'name', 'latitude_deg', 'longitude_deg',
       'elevation_ft', 'continent', 'iso_country', 'iso_region',
       'municipality', 'scheduled_service', 'icao_code', 'iata_code',
       'gps_code', 'local_code', 'home_link', 'wikipedia_link', 'keywords'],
      dtype='str')

In [47]:
airp.dtypes

id                     int64
ident                    str
type                     str
name                     str
latitude_deg         float64
longitude_deg        float64
elevation_ft         float64
continent                str
iso_country              str
iso_region               str
municipality             str
scheduled_service        str
icao_code                str
iata_code                str
gps_code                 str
local_code               str
home_link                str
wikipedia_link           str
keywords                 str
dtype: object

In [48]:
airp.info()

<class 'pandas.DataFrame'>
RangeIndex: 84934 entries, 0 to 84933
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 84934 non-null  int64
 1   ident              84934 non-null  str
 2   type               84934 non-null  str
 3   name               84934 non-null  str
 4   latitude_deg       84934 non-null  float64
 5   longitude_deg      84934 non-null  float64
 6   elevation_ft       70230 non-null  float64
 7   continent          45444 non-null  str
 8   iso_country        84642 non-null  str
 9   iso_region         84934 non-null  str
 10  municipality       80177 non-null  str
 11  scheduled_service  84934 non-null  str
 12  icao_code          9816 non-null   str
 13  iata_code          9063 non-null   str
 14  gps_code           43996 non-null  str
 15  local_code         35985 non-null  str
 16  home_link          4661 non-null   str
 17  wikipedia_link     16670 non-null  str
 18  keywords           21067 non-null  str
dtypes: float64(3), int64(1), str(15)
memory usage: 18.9 MB

<p>Airport identifiers (Idents) are unique codes designating airports worldwide, 
primarily IATA (3-letter) and ICAO (4-letter) codes used for identification, 
flight planning, and navigation.</p>

<p>Check for possible duplicates for the key column</p>

In [49]:
airp_duplicated = airp[airp['ident'].duplicated(keep=False)]

In [50]:
airp_duplicated

Empty DataFrame
Columns: [id, ident, type, name, latitude_deg, longitude_deg, elevation_ft, continent, iso_country, iso_region, municipality, scheduled_service, icao_code, iata_code, gps_code, local_code, home_link, wikipedia_link, keywords]
Index: []